from pydantic import BaseModel
from typing import Optional

class SQLEvaluationEntry(BaseModel):
    """
    A Pydantic model to represent a SQL test case.

    Args:
        db_path: str -- Path to the database
        generated_sql: str -- SQL query generated by the model
        gold_sql: str -- Ground truth SQL query
        question: str -- Natural language question corresponding to the SQL query
        isCorrect: Optional[bool] = None -- Whether the generated SQL matches the ground truth
    """
    db_path: str
    generated_sql: str
    gold_sql: str
    question: str
    isCorrect: Optional[bool] = None
